# Dependencies
markdown:         kramdown
redcarpet:
  extensions: 	  ["no_intra_emphasis", "lax_spacing", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Java and C# Programming musings
tagline:          Ilya Palopezhentsev
url:              https://ipalopezhentsev.github.io
paginate:         10
baseurl:          /
author:
  name:           Ilya Palopezhentsev
  #url:            https://twitter.com/mdo
  email:          iliks@mail.ru

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ipalopezhentsev

pages_list:       
  About: '/about'
#  Archive: '/archive'
  Feed: '/atom.xml'
