# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Java and C# Programming musings
tagline:          Ilya Palopezhentsev
url:              http://ipalopezhentsev.github.io
paginate:         10
baseurl:          /
author:
  name:           Ilya Palopezhentsev
  #url:            https://twitter.com/mdo
  email:          iliks@mail.ru

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ipalopezhentsev

pages_list:       
  About: '/about'
#  Archive: '/archive'
  Feed: '/atom.xml'