# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Dependencies
markdown:         kramdown
#redcarpet:
#  extensions: 	  ["no_intra_emphasis", "lax_spacing", "autolink", "tables", "with_toc_data"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Programming bits
tagline:          by Ilya Palopezhentsev
url:              "https://ipalopezhentsev.github.io"
paginate:         10
baseurl:          "/"
author:
  name:           Ilya Palopezhentsev
  email:          iliks@mail.ru
google_analytics_id: UA-53591583-1


# Custom vars
github_username:  ipalopezhentsev
github:
  repo:           https://github.com/ipalopezhentsev

pages_list:       
  About: '/about'

plugins:
- jekyll-feed
- jekyll-paginate
